version: "3.2"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: WISHLIST_CORE_USER
      POSTGRES_PASSWORD: WISHLIST_CORE_PASS